#!/bin/sh
pwd=`pwd`
mkdir -p output output/problem output/scena output/stolik output/stolik2 output/latino
synfig -T3 $@ problem.sif -o output/problem/problem.png
synfig -T3 $@ scena.sif -o output/scena/scena.png
synfig -T3 $@ stolik.sif -o output/stolik/stolik.png
synfig -T3 $@ stolik2.sif -o output/stolik2/stolik2.png
synfig -T3 $@ latino.sif -o output/latino/latino.png
cat kochas.kdenlive.in | sed s~__DIR__~$pwd~ > kochas.kdenlive
